on:
  push:
      
name: Build & Publish
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out source code
        uses: actions/checkout@v2
      
      - name: Prepare GitHub release
        id: create_release
        uses: google-github-actions/release-please-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          release-type: node
          command: github-release
          package-name: ${{ github.event.repository.name }}
          
      - name: Build
        run: |
          if [ "${{steps.create_release.outputs.release_created}}" != "" ]; then
            actionVersion=${{steps.create_prod_release.outputs.tag_name}}
          else
            actionVersion="${GITHUB_REF#refs/heads/}"
          fi
          grep -rlZ __ACTION_VERSION__ . | xargs -0 sed -i -e "s/__ACTION_VERSION__/${actionVersion}/g"
          doc-resources/update-repo-docs.sh
          
          
      - name: Publish v{major}.{minor} tag
        if: steps.create_release.outputs.release_created
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{steps.release_please.outputs.major}}.${{steps.release_please.outputs.minor}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Publish v{major} tag
        if: steps.create_release.outputs.release_created
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{steps.release_please.outputs.major}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Prepare release PR
        uses: google-github-actions/release-please-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          command: release-pr
          release-type: node
          package-name: ${{ github.event.repository.name }}
          